/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.paneles;

import Control.TipoMascotaDelegado;
import Modelo.vo.TipoMascotaVo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Capacitaciones
 */
public class TipoMascotaPanel extends javax.swing.JPanel {
     private DefaultTableModel modelo;
     private final TipoMascotaVo tipoMascotaVo;
    /**
     * Creates new form TipoMascotaPanel
     */
    public TipoMascotaPanel() {
        initComponents();
        configurarTabla();
        llenarTabla(new TipoMascotaDelegado(this).consultartipomascota(), modelo);
        this.tipoMascotaVo = new TipoMascotaVo();
    }
    //metodo para obtener valores del GUIT y registrar un nuevo tipo de mascota 
    private void registrarTipoMascota(){
        //asignar el nombre del tipo de mascota
        tipoMascotaVo.setNombre(txtNombre.getText());
        tipoMascotaVo.setEstado(cbxEstado.isSelected());
        new TipoMascotaDelegado(this).insertarTipoMascota(tipoMascotaVo);
        //mensaje e confirmacion de registro
        JOptionPane.showMessageDialog(this, "Tipo de mascota Registrado", "Registro de datos",JOptionPane.INFORMATION_MESSAGE);
        refrescartabla();
        limpiarCampos();
       
    }
    // permite estblecer los parametros iniciales de una tabla
     private void configurarTabla (){
         modelo = new DefaultTableModel ();
         modelo.addColumn("id Mascota");
         modelo.addColumn("nombre");
         modelo.addColumn("estado");
         tblTipoMascota.setModel(modelo);   
         //devuelve la llave primarai
         tblTipoMascota.getSelectionModel().addListSelectionListener(tableListener);
     }
     /**
      * carga una lista de tipo de mascotas desde la BD de datos a la tbala de la interfaz grafica de usuario
      * @param listaTipoMascota lista de tipo de mascota de la BD
      * @param modelo de tabla con la estructura de los datos a cargar
      */
     private void llenarTabla(List<TipoMascotaVo> listaTipoMascota, DefaultTableModel modelo){
         for (TipoMascotaVo tipoMascotaVo : listaTipoMascota) {
             Object [] fila = new Object[3];
             fila[0] = tipoMascotaVo.getIdTipoMascota();
             fila[1] = tipoMascotaVo.getNombre();
             fila[2] = tipoMascotaVo.isEstado();
             modelo.addRow(fila);
         }
         tblTipoMascota.updateUI();
     }
     /*
     *Actauliza la informacion de la tabla con cada ves que se realiza
     *un registro 
     */
          private void refrescartabla(){
              modelo.setRowCount(0);
              List<TipoMascotaVo> listaMascota = new TipoMascotaDelegado(this).consultartipomascota();
              llenarTabla(listaMascota, modelo); 
     }
          private void limpiarCampos(){
              txtNombre.setText("");
              cbxEstado.setSelected(false);
          }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoMascota = new javax.swing.JTable();
        cbxEstado = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("Nombre");

        jLabel2.setText("Estado");

        tblTipoMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTipoMascota);

        cbxEstado.setText("Activo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxEstado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnGuardar)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.registrarTipoMascota();
    }//GEN-LAST:event_btnGuardarActionPerformed
    ListSelectionListener tableListener= new ListSelectionListener() {
         @Override
         public void valueChanged(ListSelectionEvent e) {
            if (tblTipoMascota.getSelectedRow()> - 1){
                //se obtiene el id da fila seleccionada en la tabla
                int id = (int) tblTipoMascota.getValueAt(tblTipoMascota.getSelectedRow(), 0);
                //consultar en la BD por ese id seleccionado y gauradr el
                //resulatado de la consulta en un nuevo objecvt de tipoMascotaVo
                TipoMascotaVo tMvo = new TipoMascotaDelegado(TipoMascotaPanel.this).consultaTipoMascota(id);
                //asignar los valiores obtenidos de la consulta a la constante
                tipoMascotaVo.setIdTipoMascota(tMvo.getIdTipoMascota());
                tipoMascotaVo.setNombre(tMvo.getNombre());
                tipoMascotaVo.setEstado(tMvo.isEstado());
                //llenar campos del formulario
                llenarCampos();
            }
         }
     };
     private  void llenarCampos(){
         txtNombre.setText(tipoMascotaVo.getNombre());
         cbxEstado.setSelected(tipoMascotaVo.isEstado());
           
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox cbxEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblTipoMascota;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    }

